"""initial_sqlmodel_schema

Revision ID: 23db127ccf59
Revises:
Create Date: 2026-09-20 21:46:05.929863

"""

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "23db127ccf59"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bills",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sejm_print_num", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("author", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("document_url", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_bills_sejm_print_num"), "bills", ["sejm_print_num"], unique=False)
    op.create_index(op.f("ix_bills_status"), "bills", ["status"], unique=False)
    op.create_table(
        "mps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("last_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("club", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mps_active"), "mps", ["active"], unique=False)
    op.create_index(op.f("ix_mps_club"), "mps", ["club"], unique=False)
    op.create_table(
        "promises",
        sa.Column("id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("party", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("NEW", "IN_PROGRESS", "FULFILLED", "BROKEN", name="promisestatus"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_promises_category"), "promises", ["category"], unique=False)
    op.create_index(op.f("ix_promises_party"), "promises", ["party"], unique=False)
    op.create_index(op.f("ix_promises_status"), "promises", ["status"], unique=False)
    op.create_index(op.f("ix_promises_title"), "promises", ["title"], unique=False)
    op.create_table(
        "votings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sitting_num", sa.Integer(), nullable=False),
        sa.Column("voting_num", sa.Integer(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_votings_date"), "votings", ["date"], unique=False)
    op.create_index(op.f("ix_votings_sitting_num"), "votings", ["sitting_num"], unique=False)
    op.create_index(op.f("ix_votings_voting_num"), "votings", ["voting_num"], unique=False)
    op.create_table(
        "llm_evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("promise_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bill_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "alignment_status",
            sa.Enum("W_PELNI", "CZESCIOWO", "SPRZECZNA", "BRAK_POWIAZANIA", name="alignmentstatus"),
            nullable=False,
        ),
        sa.Column("justification", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("confidence_score", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.id"],
        ),
        sa.ForeignKeyConstraint(
            ["promise_id"],
            ["promises.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_llm_evaluations_alignment_status"),
        "llm_evaluations",
        ["alignment_status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_llm_evaluations_bill_id"), "llm_evaluations", ["bill_id"], unique=False
    )
    op.create_index(
        op.f("ix_llm_evaluations_promise_id"), "llm_evaluations", ["promise_id"], unique=False
    )
    op.create_table(
        "mp_votes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("voting_id", sa.Integer(), nullable=False),
        sa.Column("mp_id", sa.Integer(), nullable=False),
        sa.Column(
            "vote_type", sa.Enum("YES", "NO", "ABSTAIN", "ABSENT", name="votetype"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["mp_id"],
            ["mps.id"],
        ),
        sa.ForeignKeyConstraint(
            ["voting_id"],
            ["votings.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mp_votes_mp_id"), "mp_votes", ["mp_id"], unique=False)
    op.create_index(op.f("ix_mp_votes_vote_type"), "mp_votes", ["vote_type"], unique=False)
    op.create_index(op.f("ix_mp_votes_voting_id"), "mp_votes", ["voting_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mp_votes_voting_id"), table_name="mp_votes")
    op.drop_index(op.f("ix_mp_votes_vote_type"), table_name="mp_votes")
    op.drop_index(op.f("ix_mp_votes_mp_id"), table_name="mp_votes")
    op.drop_table("mp_votes")
    op.drop_index(op.f("ix_llm_evaluations_promise_id"), table_name="llm_evaluations")
    op.drop_index(op.f("ix_llm_evaluations_bill_id"), table_name="llm_evaluations")
    op.drop_index(op.f("ix_llm_evaluations_alignment_status"), table_name="llm_evaluations")
    op.drop_table("llm_evaluations")
    op.drop_index(op.f("ix_votings_voting_num"), table_name="votings")
    op.drop_index(op.f("ix_votings_sitting_num"), table_name="votings")
    op.drop_index(op.f("ix_votings_date"), table_name="votings")
    op.drop_table("votings")
    op.drop_index(op.f("ix_promises_title"), table_name="promises")
    op.drop_index(op.f("ix_promises_status"), table_name="promises")
    op.drop_index(op.f("ix_promises_party"), table_name="promises")
    op.drop_index(op.f("ix_promises_category"), table_name="promises")
    op.drop_table("promises")
    op.drop_index(op.f("ix_mps_club"), table_name="mps")
    op.drop_index(op.f("ix_mps_active"), table_name="mps")
    op.drop_table("mps")
    op.drop_index(op.f("ix_bills_status"), table_name="bills")
    op.drop_index(op.f("ix_bills_sejm_print_num"), table_name="bills")
    op.drop_table("bills")
    # ### end Alembic commands ###
