"""add_osr_and_revisions

Revision ID: 960864ff1906
Revises: 23db127ccf59
Create Date: 2026-09-20 21:53:22.488598

"""

from collections.abc import Sequence

import pgvector  # noqa: F401
import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "960864ff1906"
down_revision: str | None = "23db127ccf59"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "bill_articles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("bill_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("article_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("raw_text", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(dim=1536), nullable=True),
        sa.ForeignKeyConstraint(
            ["bill_id"],
            ["bills.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_bill_articles_article_number"), "bill_articles", ["article_number"], unique=False
    )
    op.create_index(op.f("ix_bill_articles_bill_id"), "bill_articles", ["bill_id"], unique=False)
    op.create_table(
        "promise_revisions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("promise_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("content_hash", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("full_html_content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("scraped_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["promise_id"],
            ["promises.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_promise_revisions_content_hash"),
        "promise_revisions",
        ["content_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_promise_revisions_promise_id"), "promise_revisions", ["promise_id"], unique=False
    )
    op.create_index(
        op.f("ix_promise_revisions_scraped_at"), "promise_revisions", ["scraped_at"], unique=False
    )
    op.add_column("bills", sa.Column("estimated_budget_impact_pln", sa.Float(), nullable=True))
    op.add_column(
        "bills", sa.Column("osr_summary", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bills", "osr_summary")
    op.drop_column("bills", "estimated_budget_impact_pln")
    op.drop_index(op.f("ix_promise_revisions_scraped_at"), table_name="promise_revisions")
    op.drop_index(op.f("ix_promise_revisions_promise_id"), table_name="promise_revisions")
    op.drop_index(op.f("ix_promise_revisions_content_hash"), table_name="promise_revisions")
    op.drop_table("promise_revisions")
    op.drop_index(op.f("ix_bill_articles_bill_id"), table_name="bill_articles")
    op.drop_index(op.f("ix_bill_articles_article_number"), table_name="bill_articles")
    op.drop_table("bill_articles")
    # ### end Alembic commands ###
